### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danielperez9430**
Add toString().

### CODE REVIEW

**Comment by danielperez9430** [comment]
toLowerCase function only exists on strings. You can call toString() on anything in javascript to get a string representation

**Comment by danielperez9430** [comment]
TypeError: Cannot read property 'toLowerCase' of undefined
    at TelegramBot.bot.on (C:\Users\dpefe\Desktop\escritorio\bot-node\lisa.js:29:14)
    at TelegramBot.emit (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\eventemitter3\index.js:150:33)
    at TelegramBot.processUpdate (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\node-telegram-bot-api\src\telegram.js:460:12)
    at updates.forEach.update (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\node-telegram-bot-api\src\telegramPolling.js:96:20)
    at Array.forEach (<anonymous>)
    at _lastRequest._getUpdates.then.updates (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\node-telegram-bot-api\src\telegramPolling.js:93:17)
    at tryCatcher (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\dpefe\Desktop\escritorio\bot-node\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)

**Comment by danielperez9430** [comment]
The  error is fixed Add toString().

**Comment by hosein2398** [comment]
Right, thanks.

**Pull request merged**
